//ADDING QUESTIONS BY STORING THEM IN AN ARRAY OF OBJECTS
//SETTING UP THE CLI INPUT
//INITIALIZING THE GAME VARIABLES
//ASKING THE QUESTIONS
//CHECKING THE ANSWERS
//CHECKING THE SCORE
//ENDING THE GAME
//STARTING THE GAME
